import React, { createContext, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LangType = 'uk' | 'en' | 'ru';

const translations = {
  uk: {
    // NAV
    home: 'Головна',
    search: 'Пошук',
    settings: 'Налаштування',
    profile: 'Профіль',
    // HOME
    chatTechnicians: 'Чат Техніків',
    techCard: 'Тех-Карта',
    colorAnalysis: 'Аналіз кольору',
    newOrder: '📋 Новий наряд',
    // AUTH
    login: 'Вхід',
    register: 'Реєстрація',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Підтвердіть пароль',
    name: 'Імʼя',
    enterLogin: 'Увійти',
    enterRegister: 'Зареєструватися',
    forgotPassword: 'Забули пароль?',
    passwordResetSent: 'Лист надіслано',
    passwordResetMsg: 'Перевірте пошту та дотримуйтесь інструкцій',
    doctor: 'Лікар',
    technician: 'Технік',
    // PROFILE
    personalData: 'Особисті дані',
    firstName: 'Імʼя',
    lastName: 'Прізвище',
    position: 'Посада',
    aboutLab: 'Про лабораторію',
    labName: 'Назва лабораторії',
    city: 'Місто',
    experience: 'Стаж роботи (років)',
    specialization: 'Спеціалізація',
    statistics: 'Статистика',
    orders: 'Замовлень',
    colorAnalyses: 'Аналізів кольору',
    saveProfile: 'Зберегти профіль',
    logout: '🚪 Вийти з акаунту',
    logoutTitle: 'Вихід з акаунту',
    logoutConfirm: 'Ви впевнені, що хочете вийти?',
    cancel: 'Скасувати',
    exit: 'Вийти',
    uploadPhoto: 'Завантажити фото',
    chooseAvatar: 'Обрати аватар',
    chooseFromGallery: 'Обрати з галереї',
    saved: 'Збережено',
    profileSaved: 'Профіль збережено',
    error: 'Помилка',
    // POSITIONS
    posDentist: 'Зубний технік',
    posTechnologist: 'Технолог',
    posManager: 'Керівник лабораторії',
    posOther: 'Інше',
    // SPECIALIZATIONS
    specCeramic: 'Металокераміка',
    specZircon: 'Цирконій',
    specComposite: 'Композит',
    specBugel: 'Бюгель',
    specRemovable: 'Знімні протези',
    // COLOR ANALYZER
    vitaAnalysis: 'Аналіз кольору VITA',
    takePhoto: 'Сфотографувати',
    fromGallery: 'З галереї',
    recommendations: '💡 Рекомендації для точного результату',
    analyze: '🔍 Аналізувати',
    analyzing: 'Аналізую...',
    vitaShade: 'Відтінок VITA',
    confidence: 'Впевненість',
    photoQuality: 'Якість фото',
    description: 'Опис',
    subtones: 'Супутні субтони',
    zones: 'Зони',
    cervical: 'Шийка',
    body: 'Тіло',
    incisalEdge: 'Ріжучий край',
    saveToOrder: '✓ Зберегти в наряд',
    analyzeAgain: '🔄 Аналізувати знову',
    addSmilePhoto: '📸 Додати фото посмішки',
    // SETTINGS
    settingsTitle: 'Налаштування',
    appearance: 'Зовнішній вигляд',
    darkTheme: 'Темна тема',
    lightTheme: 'Світла тема',
    language: 'Мова',
    notifications: 'Сповіщення',
    pushNotifications: 'Push-сповіщення',
    security: 'Безпека',
    changePassword: 'Змінити пароль',
    aboutApp: 'Про додаток',
    version: 'Версія',
    privacyPolicy: 'Політика конфіденційності',
    support: 'Написати в підтримку',
  },
  en: {
    home: 'Home',
    search: 'Search',
    settings: 'Settings',
    profile: 'Profile',
    chatTechnicians: 'Technicians Chat',
    techCard: 'Tech Card',
    colorAnalysis: 'Color Analysis',
    newOrder: '📋 New Order',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Name',
    enterLogin: 'Sign In',
    enterRegister: 'Sign Up',
    forgotPassword: 'Forgot password?',
    passwordResetSent: 'Email sent',
    passwordResetMsg: 'Check your email and follow the instructions',
    doctor: 'Doctor',
    technician: 'Technician',
    personalData: 'Personal Data',
    firstName: 'First Name',
    lastName: 'Last Name',
    position: 'Position',
    aboutLab: 'About Laboratory',
    labName: 'Laboratory Name',
    city: 'City',
    experience: 'Experience (years)',
    specialization: 'Specialization',
    statistics: 'Statistics',
    orders: 'Orders',
    colorAnalyses: 'Color Analyses',
    saveProfile: 'Save Profile',
    logout: '🚪 Sign Out',
    logoutTitle: 'Sign Out',
    logoutConfirm: 'Are you sure you want to sign out?',
    cancel: 'Cancel',
    exit: 'Sign Out',
    uploadPhoto: 'Upload Photo',
    chooseAvatar: 'Choose Avatar',
    chooseFromGallery: 'Choose from Gallery',
    saved: 'Saved',
    profileSaved: 'Profile saved',
    error: 'Error',
    posDentist: 'Dental Technician',
    posTechnologist: 'Technologist',
    posManager: 'Lab Manager',
    posOther: 'Other',
    specCeramic: 'Metal-Ceramic',
    specZircon: 'Zirconia',
    specComposite: 'Composite',
    specBugel: 'Clasp',
    specRemovable: 'Removable Dentures',
    vitaAnalysis: 'VITA Color Analysis',
    takePhoto: 'Take Photo',
    fromGallery: 'From Gallery',
    recommendations: '💡 Tips for accurate result',
    analyze: '🔍 Analyze',
    analyzing: 'Analyzing...',
    vitaShade: 'VITA Shade',
    confidence: 'Confidence',
    photoQuality: 'Photo Quality',
    description: 'Description',
    subtones: 'Secondary Subtones',
    zones: 'Zones',
    cervical: 'Cervical',
    body: 'Body',
    incisalEdge: 'Incisal Edge',
    saveToOrder: '✓ Save to Order',
    analyzeAgain: '🔄 Analyze Again',
    addSmilePhoto: '📸 Add Smile Photo',
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    darkTheme: 'Dark Theme',
    lightTheme: 'Light Theme',
    language: 'Language',
    notifications: 'Notifications',
    pushNotifications: 'Push Notifications',
    security: 'Security',
    changePassword: 'Change Password',
    aboutApp: 'About App',
    version: 'Version',
    privacyPolicy: 'Privacy Policy',
    support: 'Contact Support',
  },
  ru: {
    home: 'Главная',
    search: 'Поиск',
    settings: 'Настройки',
    profile: 'Профиль',
    chatTechnicians: 'Чат Техников',
    techCard: 'Тех-Карта',
    colorAnalysis: 'Анализ цвета',
    newOrder: '📋 Новый наряд',
    login: 'Вход',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    name: 'Имя',
    enterLogin: 'Войти',
    enterRegister: 'Зарегистрироваться',
    forgotPassword: 'Забыли пароль?',
    passwordResetSent: 'Письмо отправлено',
    passwordResetMsg: 'Проверьте почту и следуйте инструкциям',
    doctor: 'Врач',
    technician: 'Техник',
    personalData: 'Личные данные',
    firstName: 'Имя',
    lastName: 'Фамилия',
    position: 'Должность',
    aboutLab: 'О лаборатории',
    labName: 'Название лаборатории',
    city: 'Город',
    experience: 'Стаж работы (лет)',
    specialization: 'Специализация',
    statistics: 'Статистика',
    orders: 'Заказов',
    colorAnalyses: 'Анализов цвета',
    saveProfile: 'Сохранить профиль',
    logout: '🚪 Выйти из аккаунта',
    logoutTitle: 'Выход из аккаунта',
    logoutConfirm: 'Вы уверены, что хотите выйти?',
    cancel: 'Отмена',
    exit: 'Выйти',
    uploadPhoto: 'Загрузить фото',
    chooseAvatar: 'Выбрать аватар',
    chooseFromGallery: 'Выбрать из галереи',
    saved: 'Сохранено',
    profileSaved: 'Профиль сохранён',
    error: 'Ошибка',
    posDentist: 'Зубной техник',
    posTechnologist: 'Технолог',
    posManager: 'Руководитель лаборатории',
    posOther: 'Другое',
    specCeramic: 'Металлокерамика',
    specZircon: 'Циркон',
    specComposite: 'Композит',
    specBugel: 'Бюгель',
    specRemovable: 'Съёмные протезы',
    vitaAnalysis: 'Анализ цвета VITA',
    takePhoto: 'Сфотографировать',
    fromGallery: 'Из галереи',
    recommendations: '💡 Рекомендации для точного результата',
    analyze: '🔍 Анализировать',
    analyzing: 'Анализирую...',
    vitaShade: 'Оттенок VITA',
    confidence: 'Уверенность',
    photoQuality: 'Качество фото',
    description: 'Описание',
    subtones: 'Сопутствующие субтоны',
    zones: 'Зоны',
    cervical: 'Шейка',
    body: 'Тело',
    incisalEdge: 'Режущий край',
    saveToOrder: '✓ Сохранить в наряд',
    analyzeAgain: '🔄 Анализировать заново',
    addSmilePhoto: '📸 Добавить фото улыбки',
    settingsTitle: 'Настройки',
    appearance: 'Внешний вид',
    darkTheme: 'Тёмная тема',
    lightTheme: 'Светлая тема',
    language: 'Язык',
    notifications: 'Уведомления',
    pushNotifications: 'Push-уведомления',
    security: 'Безопасность',
    changePassword: 'Сменить пароль',
    aboutApp: 'О приложении',
    version: 'Версия',
    privacyPolicy: 'Политика конфиденциальности',
    support: 'Написать в поддержку',
  },
};

export type TranslationKeys = keyof typeof translations.ru;

const LanguageContext = createContext<{
  lang: LangType;
  t: (key: TranslationKeys) => string;
  setLang: (lang: LangType) => void;
}>({
  lang: 'uk',
  t: (key) => key,
  setLang: () => {},
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<LangType>('uk');

  useEffect(() => {
    AsyncStorage.getItem('language').then((saved) => {
      if (saved === 'uk' || saved === 'en' || saved === 'ru') {
        setLangState(saved);
      }
    });
  }, []);

  const setLang = async (newLang: LangType) => {
    setLangState(newLang);
    await AsyncStorage.setItem('language', newLang);
  };

  const t = (key: TranslationKeys): string => {
    return translations[lang][key] ?? translations['ru'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
